kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus-k8s
  labels:
    app.kubernetes.io/name: prometheus
subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: microshift-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-k8s
