apiVersion: v1
data:
  prometheus.yml: |
    # my global config
    global:
      scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
      evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
      # scrape_timeout is set to the global default (10s).
      

    remote_write:
      - url: "https://thanos-receiver-multicluster-monitoring.apps.ocp411-dev.cloudlet-dev.com/api/v1/receive"
        tls_config:
          insecure_skip_verify: true 

    # A scrape configuration containing exactly one endpoint to scrape:
    # Here it's Prometheus itself.
    scrape_configs:
      # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
      - job_name: "prometheus"

        # metrics_path defaults to '/metrics'
        # scheme defaults to 'http'.

        static_configs:
          - targets: ["localhost:9090"]

      - job_name: 'openshift-platform'
        scrape_interval: 30s
        scrape_timeout: 20s
        honor_labels: true
        metrics_path: '/metrics'
        static_configs:
          - targets:
            - 'kube-state-metrics.microshift-monitoring.svc:8080'
            labels:
              cluster_name: 'microshift'

      - job_name: 'node-exporter'
        scrape_interval: 30s
        scrape_timeout: 20s
        honor_labels: true
        metrics_path: '/metrics'
        static_configs:
          - targets:
            - 'node-exporter-metrics.microshift-monitoring.svc:9100'
            labels:
              cluster_name: 'microshift'

      - job_name: 'kubelet'
        scrape_interval: 30s
        scrape_timeout: 20s
        honor_labels: true
        scheme: https
        tls_config:
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        metrics_path: '/metrics/cadvisor'
        static_configs:
          - targets:
            - '127.0.0.1:10250'
            labels:
              cluster_name: 'microshift'
    
kind: ConfigMap
metadata:
  name: prometheus
  namespace: microshift-monitoring
