{
 "title": "MicroShift",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Kubernetes Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Services in openshift-dns Namespace",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "kube_service_info{cluster_name=\"microshift\",namespace=\"openshift-dns\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Scheduled Pods",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_scheduled{cluster_name=\"microshift\"})",
     "legendFormat": "Scheduled Pods"
    }
   ]
  },
  { "title": "Node Exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "MicroShift Node Active Memory (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_Active_bytes{cluster_name=\"microshift\"}",
     "legendFormat": "Active Bytes"
    }
   ]
  },
  {
   "title": "Available Space in '/' Filesystem (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{device=~\"/dev/mapper/.*\",mountpoint=\"/\"}",
     "legendFormat": "Available Bytes"
    }
   ]
  },
  {
   "title": "Network Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transmit Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{cluster_name=\"microshift\"}[5m])) by (interface)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Receive Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total{cluster_name=\"microshift\"}[5m])) by (interface)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Transmit Packets",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_packets_total{cluster_name=\"microshift\"}[5m])) by (interface)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Receive Packets",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_packets_total{cluster_name=\"microshift\"}[5m])) by (interface)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Compute Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Monitoring Stack Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster_name=\"microshift\",namespace=\"microshift-monitoring\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Monitoring Stack CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\", cluster_name=\"microshift\",namespace=\"microshift-monitoring\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}